"""add water

Revision ID: e4b13f548813
Revises: bd17fb05d6ce
Create Date: 2025-10-16 13:21:03.408622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_water'
down_revision: Union[str, Sequence[str], None] = 'bd17fb05d6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('water_drinked_ml', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'water_drinked_ml')
    # ### end Alembic commands ###
