version: "3.9"

services:
  app:
    build: .
    container_name: nutritrack_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    network_mode: "host"
